language: node_js
env:
  global:
    - DISPLAY=:99.0
node_js:
  - "0.10"
before_install:
  - "npm install -g casperjs"
before_script:
  - "node test/server.js &"
  - "sleep 2"
  - "ps -fA | grep node"
script:
  - "npm test"
after_script:
  - "ps -fA | grep node"
notifications:
  email: alessandro.nadalin@gmail.com